variable "env_name" {}
variable "ami_name" {}
variable "sg_name" {}
variable "comp" {}
#variable "name" {}
variable "domain_name" {}
variable "private_zone" {}
variable "vault_token" {}
variable "on_demand_count" {}
variable "spot_count" {}